### ISSUE TITLE
problem with quick shop

### ISSUE THREAD

**Issue by Randall-Rut** [YiC200333/XConomy#69] opened 2022-07-11 01:15 UTC
**Version of XConomy**  
XConomy V2.18.14

**Server version**  
Purpur 1.19.0

**Storage-type**  
MySQL

**Describe the issues**  
hello there is a problem with quickshop, but the error only affects the console... in the game the transactions work fine without problem, but it gives that error on the console every time you interact with a quickshop store

[QuickShop] This seems not a QuickShop error. If you have any question, you may can ask QuickShop developer but don't except any solution.
[17:43:33 WARN]: [QuickShop] QuickShop received an error when processing Economy response, THIS NOT A QUICKSHOP FAULT, you might need ask help with your Economy Provider plugin (XConomy) author.
java.lang.NullPointerException: Cannot invoke "me.yic.xconomy.utils.PlayerData.getUniqueId()" because "pd" is null
        at me.yic.xconomy.data.DataCon.changeplayerdata(DataCon.java:94) ~[XConomy-Bukkit-2.18.14.jar:?]
        at me.yic.xconomy.depend.economy.Vault.depositPlayer(Vault.java:159) ~[XConomy-Bukkit-2.18.14.jar:?]
        at org.maxgamer.quickshop.economy.Economy_Vault.deposit(Economy_Vault.java:145) ~[QuickShop-5.1.0.9.jar:?]
        at org.maxgamer.quickshop.api.economy.EconomyTransaction.commit(EconomyTransaction.java:190) ~[QuickShop-5.1.0.9.jar:?]
        at org.maxgamer.quickshop.api.economy.EconomyTransaction.commit(EconomyTransaction.java:142) ~[QuickShop-5.1.0.9.jar:?]
        at org.maxgamer.quickshop.api.economy.EconomyTransaction.failSafeCommit(EconomyTransaction.java:129) ~[QuickShop-5.1.0.9.jar:?]
        at org.maxgamer.quickshop.shop.SimpleShopManager.actionBuy(SimpleShopManager.java:708) ~[QuickShop-5.1.0.9.jar:?]
        at org.maxgamer.quickshop.shop.SimpleShopManager.actionTrade(SimpleShopManager.java:1423) ~[QuickShop-5.1.0.9.jar:?]
        at org.maxgamer.quickshop.shop.SimpleShopManager.lambda$handleChat$4(SimpleShopManager.java:495) ~[QuickShop-5.1.0.9.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.jar:git-Purpur-1703]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.19.jar:git-Purpur-1703]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1517) ~[purpur-1.19.jar:git-Purpur-1703]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:485) ~[purpur-1.19.jar:git-Purpur-1703]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1441) ~[purpur-1.19.jar:git-Purpur-1703]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1208) ~[purpur-1.19.jar:git-Purpur-1703]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:307) ~[purpur-1.19.jar:git-Purpur-1703]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

---

**(option)XConomy's config.yml**

#Default Online Offline SemiOnline
#Default mode will automatically detect the player's UUID(support GeyserMC)
#Online mode is better for servers that enable online-mode(support Yggdrasil)
#Offline mode does not support ignoring username case
UUID-mode: Default
#In convertion mode, can use command '/xconomy' import data from other plugins based on Vault
#Conflicting data will be skipped, The imported data will be saved in XConomy/importdata/data.yml
#In this mode, XConomy will not start normally
#After the conversion, please check data and turn off this mode
importdata-mode: false

#Settings
Settings:
  #Chinese ChineseTW English French Spanish Russian Turkish Japanese German Indonesia Portuguese
  language: Spanish
  #Whether to check for new version
  check-update: true
  #TOP10 and the Server Total refresh time interval (Seconds)
  refresh-time: 300
  #If set to true, XConomy will register the following commands:
    # - economy
    # - eco
    # - ebalancetop
    # - ebaltop
    # - eeconomy
  #Please keep in mind that if Essentials is installed on your server
  #XConomy will take over these commands.
  eco-command: true
  #XConomy will disable the economic function of Essentials.
  #Just the economic function.
  disable-essentials: true
  #Initial balance
  initial-bal: 5000
  #Tax to be paid for pay command (0.5 means 50%, 1 means 100%)
  payment-tax: 0
  #Ranking size (Max value 100)
  ranking-size: 60
  #Rows per page of list (Ranking and help menu)
  lines-per-page: 10
  #If you need to modify the data in the database directly, it is recommended to enable it
  #Disabling caching will increase the pressure on the database
  disable-cache: true
  #Dose save transaction record
  #Only MySQL is supported
  transaction-record: false
  #Record transaction information of pay command while player offline.
  #The player will receive tips when they reconnect.
  #Transaction-record function must be enabled.
  offline-pay-transfer-tips: true
  #Ignore the case of player names
  username-ignore-case: false

#It can solve the problem that some plugins need to create non-player accounts, such as Factions,Towny
#Non-player account data is not synced with BC
non-player-account:
  #Whether to enable non-player accounts.
  enable: false
  #If the account name contains fields in the whitelist, it will be recognized as non-player accounts.
  #Otherwise, it is recognized as a player account
  #If the player's name contains fields in the whitelist, it will be denied access to the server.
  #This function can reduce the times that reading data from the database.
  whitelist:
    #Whether to enable whitelist.
    enable: true
    fields-list:
    - town-
    - towny-
    - nation-
    - qs-
    - quickshop-

#The display of the currency
Currency:
  singular-name: colon
  plural-name: colones
  #Is the balance an integer
  integer-bal: false
  thousands-separator: ','
  #%format_balance% indicate the balance after the format
  display-format: '%balance% %currencyname%'
  #Maximum amount (default is maximum)
  max-number: '10000000000000000'
  format-balance:
    1000: k
    1000000: m

**(option)Screenshots**
![Captura de pantalla (80)](https://user-images.githubusercontent.com/96611787/178171124-b51e34f2-aad5-4062-a631-40555b3c9cf4.png)

**Comment by YiC200333** [comment] 2022-07-13 13:32
The problem is fixed in version 2.19

**Closed as completed** 2022-07-13 13:33 UTC
Labels: bug
